### ISSUE TITLE
Error when enter in game

### ISSUE THREAD

**Issue by AndrasHPataki** [joe7575/signs_bot#15]
Before this error, i only put the cart sensor on the ground... now, i cant enter on the world before this error raise
![error](https://user-images.githubusercontent.com/33844385/147675676-30547399-4058-40eb-a723-f3d28e442e51.png)

**Comment by joe7575** [comment]
There was a hard dependency to the mod 'minecart'. The dependency is now optional. You can install the mod minecart or the cart sensor is now disabled.
