### ISSUE TITLE
signs_bot:changer1 crashing game when used on Signs Bot Box

### ISSUE THREAD

**Issue by Jury-Me** [joe7575/signs_bot#27]
Found strange behavior of the Bot Control Unit, if you try to activate it pointing at Signs Bot Box, it will crash the game.

AsyncErr: Lua: Runtime error from mod 'default' in callback node_on_timer(): /home/jury/.minetest/mods/signs_bot/basis.lua:432: attempt to index local 'placer' (a nil value)
stack traceback:
	/home/jury/.minetest/mods/signs_bot/basis.lua:432: in function 'after_place_node'
	/home/jury/.minetest/mods/signs_bot/lib.lua:182: in function 'place_sign'
	/home/jury/.minetest/mods/signs_bot/changer.lua:84: in function 'signs_bot_on_signal'
	/home/jury/.minetest/mods/signs_bot/signal.lua:69: in function 'send_signal'
	/home/jury/.minetest/mods/signs_bot/node_sensor.lua:107: in function </home/jury/.minetest/mods/signs_bot/node_sensor.lua:104>

https://user-images.githubusercontent.com/71692635/222988151-f0ab8a9b-0657-4618-919f-25752f4d005d.mp4

Also, Signs Bot cannot properly place techpack machines? Just thought it great for automatic building of tileable machines set ups, but when I tried, Bot places machines like simple blocks, it's doesn't have number or interface.

**Comment by joe7575** [comment]
The issue is fixed, the request "Signs Bot cannot properly place techpack machines" is not that easy and more effort
