### ISSUE TITLE
Serverressources

### ISSUE THREAD

**Issue by acmgit** [joe7575/signs_bot#29]
As i profiled my server, i was wondering, that the sign_bots consume many time, when the bots are to remove.
Ok, there are many bots active, but i was wondering, that the bots waste a lot of time at this procedure.

Greetings, Clyde.

Take a look at part avg %.
[profile-20230603T202016.csv](https://github.com/joe7575/signs_bot/files/11691733/profile-20230603T202016.csv)

**Comment by joe7575** [comment]
This code came as a PR and is actually not necessary unless you keep crashing the server :=)

**Comment by joe7575** [comment]
I saw that you use "areas" as a protection mod. I have decided not to use "areas" as the performance decreases with each additional area. Can you measure the average time taken to call `minetest.is_protected`?
