### ISSUE TITLE
Farming

### ISSUE THREAD

**Issue by Stalker50511** [joe7575/signs_bot#32]
Hi.

I have a problem where when the bot finishes harvesting cotton and wheat and when it's being sowed it is planted in growth stage 1 and doesn't grow any further.

**Comment by joe7575** [comment]
Have you installed the mod "Ethereal NG"?

**Comment by Stalker50511** [comment]
I got it shorted. i had default minetest farming. after installing farming redo mod it worked.

**Comment by joe7575** [comment]
Thanks for your feedback. I will test it without farming redo

**Comment by joe7575** [comment]
Should be fixed now
