### ISSUE TITLE
pattern/copy 5x3 is off center

### ISSUE THREAD

**Issue by gd2shoe** [joe7575/signs_bot#36]
This:
```
turn_right
pattern
turn_around
copy 5x3
turn_off
```
Produces [this](https://www.dropbox.com/scl/fi/ygye1lahk2vp4j2yej9qv/screenshot_20231028_102202.png?rlkey=o4311eh94qua09rp9i1vaff4b&dl=0).  The leftmost blocks are omitted, and extra blocks are copied to the right.  For reference, [this](https://www.dropbox.com/scl/fi/kr3kmopanqzdsykq7v35y/screenshot_20231028_103039.png?rlkey=wzupki2qc3vwybtuo1rz8gjag&dl=0) is what 3x3 looks like.  I believe that's correct behavior.

If I have time, I might try to hunt this down.  Which of the following is the desired outcome?  I'm guessing the first one:
[A - Copied closer](https://www.dropbox.com/scl/fi/veqryk7adtdmrk562m10l/screenshot_20231028_102329.png?rlkey=zsvuv4xn0tztyymwmfm06698h&dl=0)
[B - wysiwyg](https://www.dropbox.com/scl/fi/m30cmh0w956k7ccxy43u1/screenshot_20231028_102513.png?rlkey=luk0ixlrany9rs615eup23u05&dl=0)
[C - Consistent, back 1](https://www.dropbox.com/scl/fi/1slufsxzuvx5vux5kdgs2/screenshot_20231028_102615.png?rlkey=dmzzfkgprgcx8ur7lkpfd282c&dl=0)

**Comment by joe7575** [comment]
Thanks for the report, bug is fixed.
And yes, it should be [A - Copied closer](https://www.dropbox.com/scl/fi/veqryk7adtdmrk562m10l/screenshot_20231028_102329.png?rlkey=zsvuv4xn0tztyymwmfm06698h&dl=0)

**Comment by gd2shoe** [comment]
Awesome.  Thanks!
