### ISSUE TITLE
(minor) Bot can harvest "missing node" for player

### ISSUE THREAD

**Issue by gd2shoe** [joe7575/signs_bot#37]
I assume the glasslike "missing node" is primarily for diagnostic purposes.  It's placed by pattern/copy (and I assume other code), and it can be dug during the copy sequence, resulting in a stack of "missing node" in the bot inventory that the player can then take and place.

I don't immediately see how to abuse this, but I don' t think this is intended.  ;-)

**Comment by joe7575** [comment]
That's not a mistake, it's one of the little secrets, of which there is at least one more :)
​
But thanks for your report
