### ISSUE TITLE
Colon in print command breaks jumps

### ISSUE THREAD

**Issue by MaxSMaker** [joe7575/signs_bot#38]
A colon in a print command can break jumps:
```
print Hello:world
jump to_exit

to_exit:
print exit
exit
```
The bot will stop with the error `no return address: 'to_exit'`.

![screenshot_20240103_181856](https://github.com/joe7575/signs_bot/assets/94128604/6764ee0b-41be-46bc-8fe7-c6155fe1724a)

<details>
  <summary>But without the colon everything works fine:</summary>

```
print Hello*world
jump to_exit

to_exit:
print exit
exit
```
</details>

<details>
  <summary>In some situations this may cause the server crash:</summary>

```
print ANY:test1
print ANY:test2
print ANY:test3

jump to_exit

to_exit:
exit
```

Server crash:
```
AsyncErr: Lua: Runtime error from mod 'signs_bot' in callback node_on_timer(): ....minetest/mods/techage_modpack/signs_bot/interpreter.lua:291: bad argument #1 to 'unpack' (table expected, got nil)
stack traceback:
	[C]: in function 'unpack'
	....minetest/mods/techage_modpack/signs_bot/interpreter.lua:291: in function 'run_script'
	...st/.minetest/mods/techage_modpack/signs_bot/commands.lua:186: in function 'run_next_command'
	...etest/.minetest/mods/techage_modpack/signs_bot/basis.lua:297: in function <...etest/.minetest/mods/techage_modpack/signs_bot/basis.lua:289>
```
</details>

**Comment by joe7575** [comment]
Thanks MaxSMaker for your report.

Please test it again. If it doesn't work as expected, reopen the issue.

**Comment by MaxSMaker** [comment]
Now it works fine. Thanks!
